'use client';

import React from 'react';

import AiButton from '@/components/AiButton/AiButton.tsx';
import ModalAiContainerWrapper from '@/components/Modals/ModalAiContainerWrapper/ModalAiContainerWrapper.tsx';
import { Icons } from '@/components/common/Icons';
import { Providers } from '@/lib/providers.tsx';
import { raleway } from '@/styles/fonts';
import '@/styles/globals.css';

/*
export const metadata: Metadata = {
  title: "Bookme",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html className={`${raleway.className}`}>
        <head>
          <link rel="icon" href="/public/favicon.ico" />
        </head>
        <body className="bg-main">
          <main>{children}</main>
          <AiButton />
          <ModalAiContainerWrapper />
          <div id="modal-root"></div>
        </body>
        <Icons />
      </html>
    </Providers>
  );
}
